<?php
//registrationFormResponse.php
include("../common/document_head.html");
?>
  <body>
    <header>
      <?php
      include("../common/document_head.php");
      include("../common/mainmenu.html");
      include("../scripts/connectToDatabase.php");
      ?>
    </header>
    <main>
      <article class="Registration">
        <?php
        include("../scripts/registrationFormProcess.php");
        ?>
      </article>
    </main>
    <footer>
      <?php
      include("../common/footer.html");
      ?>
    </footer>
  </body>
</html>
